"""Initial migration

Revision ID: 66712464ead6
Revises:
Create Date: 2024-06-21 22:22:16.496764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sql.models.userModels import *


# revision identifiers, used by Alembic.
revision: str = '66712464ead6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('student_id', table_name='PlatformInfo')
    op.drop_table('PlatformInfo')
    op.drop_table('Grade')
    op.drop_index('email', table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'User', ['email'], unique=True)
    op.create_table('Grade',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('term', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type_1', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type_2', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('class_code', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('mark', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=False),
    sa.Column('point', mysql.FLOAT(), nullable=False),
    sa.Column('score_point', mysql.FLOAT(), nullable=False),
    sa.Column('prop', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('note', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('PlatformInfo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('plt_pw', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('student_id', 'PlatformInfo', ['student_id'], unique=True)
    # ### end Alembic commands ###
